### PR TITLE
works in more CMSSW versions

### PR DESCRIPTION
**Pull request by hroskes**
specifically 7_6_3 which we have on MARCC

### CODE REVIEW

**Comment by usarica** [comment]
- What is the reason for translating trimPythia to python? Can you look into resolving the seg. fault?
- Please remove loadLib and trimPyhia from gitignore. They are intended to be on this repository. If you don't like it, you can add trimPythia.pyc (see above).
- Please put another option for Pythia to include GEN. I do not agree that it should be a completely separate process.
- https://github.com/hroskes/CMSJHU_AnalysisMacros/blob/4581e084530d955552a6292c171af76cd45d6efb/JHUSpinWidthPaper_2015/LHEAnalyzer/src/HVVTree.cc#L331 is missing  || doSetAddress, see the preceding if statement.

**Comment by hroskes** [comment]
- I spent this morning trying to resolve it, but I don't have more time right now.  Maybe later.  I kept the C++ version there with a switch.
- there is a / in front of them, that means only ignore loadLib and trimPythia in this directory (which is the symbolic links created by the makefile).  The ones in macros/ are not ignored.
- Ok, this is fixed
- it doesn't need doSetAddress, if doSetAddress is true then the previous if statement triggers and g2 is added anyway.

**Comment by usarica** [comment]
Okay, let's merge when you have the time to fix it.

**Comment by hroskes** [comment]
I have a test setup here:
/home-2/jroskes1@jhu.edu/work/heshy/forUlascan
You can use the CMSSW release there.

CMSJHU_AnalysisMacros is with all my changes except I changed this line
https://github.com/usarica/CMSJHU_AnalysisMacros/pull/6/files#diff-16c89881916823e4bf622eedd2f78e93R193
to false, so it uses the C++ version of trimPythia.

You can run
./analyzer  (outdir, outfile) indir=/home-2/jroskes1@jhu.edu/work/heshy/forUlascan POWHEG_nominal-GEN_8.root maxevents=100 fileLevel=1 pythiaLevel=0 jetAlgorithm=ak8

It gives a segmentation fault

**Comment by usarica** [comment]
Hi Heshy,

I get permission denied.

Ulascan

**Comment by usarica** [comment]
I have left pythia true and changed some options (most importantly, ak5 ->ak, and there is a new deltaR option). Since I made chery-picking, I would suggest resetting your history. I am closing this PR.

**Pull request closed without merging**
